- src/net35/Radical.Windows/Presentation/Behaviors/WindowsManager.cs
- src/net35/Radical.Windows/Radical.Windows.csproj
- src/net40/Radical.Windows/Radical.Windows.csproj
- src/net45/Radical.Windows/Presentation/Behaviors/WindowsManager.cs
- src/net45/Radical.Windows/Radical.Windows.csproj
Fix #26 
@mauroservienti please check
> Remove window icon behavior

- appveyor.yml
- src/net35/Radical.Windows/Presentation/Behaviors/WindowsManager.cs
- src/net35/Radical.Windows/Presentation/Converters/EnumBooleanConverter.cs
- src/net35/Radical.Windows/Radical.Windows.csproj
- src/net40/Radical.Windows/Radical.Windows.csproj
- src/net45/Radical.Windows/Presentation/Behaviors/WindowsManager.cs
- src/net45/Radical.Windows/Radical.Windows.csproj
@micdenny please review
Fix #32
> Release 1.4.0

- appveyor.yml
* fix wrong deployment environment
* change the `unstable` build from `alpha1` to a more generic `unstable`
@micdenny please review.
> appveyor config update.

- GitVersionConfig.yaml
- appveyor.yml
- src/Radical.Windows.sln
- src/net35/Radical.Windows/Properties/AssemblyInfo.cs
- src/net35/Radical.Windows/Radical.Windows.csproj
- src/net35/Radical.Windows/packages.config
- src/net40/Radical.Windows/Radical.Windows.csproj
- src/net40/Radical.Windows/packages.config
- src/net45/Radical.Windows/Radical.Windows.csproj
- src/net45/Radical.Windows/packages.config
Connected to https://github.com/RadicalFx/housekeeping/issues/35
@micdenny this is ready for review, the goal is to [move to GitVersion](https://github.com/RadicalFx/housekeeping/issues/35) to better handle automatic versioning, especially for contributors so to avoid asking everyone to manually bump the version when opening a PR.
Please review.
> Move to gitversion

- src/net40/Radical.Windows/Presentation/Behaviors/DataGridBehavior.cs
- src/net40/Radical.Windows/Radical.Windows.csproj
- src/net45/Radical.Windows/Radical.Windows.csproj
Replaces https://github.com/RadicalFx/Radical.Windows/pull/37
Connected to #36 
@nazarenomanco please double check that the changes are what you intended.
> adding DataGrid Behavior

- src/net40/Test.Radical.Windows/Test.Radical.Windows.csproj
Connected to https://github.com/RadicalFx/housekeeping/issues/55
> differentiating test assemblies names

- src/net35/Radical.Windows/Presentation/Behaviors/MouseManager.cs
- src/net35/Radical.Windows/Radical.Windows.csproj
- src/net40/Radical.Windows/Radical.Windows.csproj
- src/net45/Radical.Windows/Radical.Windows.csproj
Fix #23 
@mauroservienti please check :smile:
> Add mousemanager

- src/net35/Radical.Windows/Presentation/Behaviors/ScrollViewerManager.cs
- src/net35/Radical.Windows/Radical.Windows.csproj
- src/net40/Radical.Windows/Radical.Windows.csproj
- src/net45/Radical.Windows/Radical.Windows.csproj
@mauroservienti please check 
Fix #25
> Add scrollviewermanager

- src/net35/Radical.Windows/Presentation/Converters/EnumBooleanConverter.cs
@mauroservienti let's start again! 
Fix #40
> Corrected EnumBooleanConverter implementation

- src/net35/Radical.Windows/Presentation/VisualTreeCrawler.cs
> Add FindChilds to VisualTreeCrawler

- src/net35/Radical.Windows/Presentation/Behaviors/ListBoxBehaviors/ScrollIntoViewForListBox.cs
- src/net35/Radical.Windows/Radical.Windows.csproj
- src/net40/Radical.Windows/Radical.Windows.csproj
- src/net45/Radical.Windows/Radical.Windows.csproj
Fix #24 Connects to https://github.com/RadicalFx/Radical.Windows/issues/53
@mauroservienti please check. Do we have to do the same for Grid and ListView?
> Add scroll into view for listbox

- src/net35/Radical.Windows/Presentation/Behaviors/WindowControlBoxBehavior.cs
- src/net35/Radical.Windows/Presentation/Behaviors/WindowsManager.cs
> Moved ShowIcon to WindowControlBoxBehavior

- src/build.cmd
- src/build.csx
- src/packages.config
- src/scripts/cmd.csx
allows to easily and quickly build via command line without opening VS
> Add local build scripts

- src/Radical.Windows/Presentation/Boot/ApplicationBootstrapper.cs
- src/Radical.Windows/Presentation/Boot/ApplicationSettings.cs
- src/Radical.Windows/Presentation/Boot/Features/AutoRegionsInjection.cs
- src/Radical.Windows/Presentation/Boot/Features/AutoSubscribe.cs
- src/Radical.Windows/Presentation/Boot/Features/Cultures.cs
- src/Radical.Windows/Presentation/Boot/Features/CurrentPrincipal.cs
- src/Radical.Windows/Presentation/Boot/Features/UIComposition.cs
- src/Radical.Windows/Presentation/Boot/IFeature.cs
> Migrate to features part of the boot process

- src/Radical.Windows/Presentation/Regions/ElementsRegion.cs
- src/Radical.Windows/Presentation/Regions/Specialized/TabControlRegion.cs
> Tabcontrol region tabitem

- src/Radical.Windows/Radical.Windows.csproj
> Make MinVerPreRelease predominant

- appveyor.yml
- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows.Tests/API/APIApprovals.cs
- src/Radical.Windows.Tests/Presentation/AbstractMementoViewModelTests.cs
- src/Radical.Windows.Tests/Presentation/AbstractValidationServiceTests.cs
- src/Radical.Windows.Tests/Presentation/AbstractViewModelTests.cs
- src/Radical.Windows/Presentation/AbstractMementoViewModel.cs
- src/Radical.Windows/Presentation/AbstractViewModel.cs
- src/Radical.Windows/Presentation/ComponentModel/IRequireValidation.cs
- src/Radical.Windows/Presentation/ComponentModel/IValidationService.cs
- src/Radical.Windows/Presentation/ComponentModel/ValidationBehavior.cs
- src/Radical.Windows/Presentation/ObjectExtensions.cs
- src/Radical.Windows/Presentation/PropertyInfoExtensions.cs
- src/Radical.Windows/Presentation/Services/Validation/AbstractValidationService.cs
- src/Radical.Windows/Presentation/Services/Validation/DataAnnotationValidationService.cs
- src/Radical.Windows/Presentation/Services/Validation/DelegateValidationService.cs
- src/Radical.Windows/Presentation/Services/Validation/NullValidationService.cs
- src/Radical.Windows/Presentation/ValidationErrorsExtensions.cs
- src/Radical.Windows/Radical.Windows.csproj
> Update to new Validator base infrastructure

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows/Presentation/Boot/ApplicationBootstrapper.cs
- src/Radical.Windows/Presentation/ComponentModel/IConventionsHandler.cs
- src/Radical.Windows/Presentation/Services/ConventionsHandler.cs
- src/Radical.Windows/Presentation/Services/ResourcesRegistrationHolder.cs
- src/Radical.Windows/Presentation/Services/ViewResolver.cs
Connected to #129 
Replaces https://github.com/RadicalFx/Radical.Windows.Presentation/pull/50
> Expose services as resources

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows.Tests/API/APIApprovals.cs
- src/Radical.Windows/ApplicationBootstrapper.cs
- src/Radical.Windows/Bootstrap/SplashScreenConfiguration.cs
> Better splash screen async API

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows/Threading/WpfDispatcher.cs
> Make WpfDispatcher internal

- src/Radical.Windows.Tests/Radical.Windows.Tests.csproj
- src/Radical.Windows/Radical.Windows.csproj
> Dependency ranges

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows.Tests/Boot/RadicalApplicationTestsWithGenericHost.cs
- src/Radical.Windows.Tests/Radical.Windows.Tests.csproj
- src/Radical.Windows/Hosting/HostBuilderExtensions.cs
- src/Radical.Windows/Hosting/RadicalApplicationService.cs
- src/Radical.Windows/Radical.Windows.csproj
- src/Radical.Windows/RadicalApplication.cs
Replaces #210 
Connected to #113
> Generic host support

- src/Radical.Windows/Bootstrap/BootstrapConventions.cs
> Added the the lookup logic for partials to use Partials as namespace segment

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows.Tests/Boot/RadicalApplicationTests.cs
- src/Radical.Windows.Tests/Boot/RadicalApplicationTestsWithGenericHost.cs
- src/Radical.Windows.Tests/Boot/SampleDependency.cs
- src/Radical.Windows/Bootstrap/BootstrapConfiguration.cs
- src/Radical.Windows/Hosting/HostBuilderExtensions.cs
- src/Radical.Windows/RadicalApplication.cs
> Add support to customize services without the need for an installer

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows.Tests/Conventions/ShouldExposeViewModelAsStaticResourceTests.cs
- src/Radical.Windows/ComponentModel/ExposeViewModelAsStaticResourceAttribute.cs
- src/Radical.Windows/Services/ConventionsHandler.cs
> Support exposing ViewModels as static resources using an attribute

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows.Tests/Presentation/Regions/Specialized/TacControlRegionTests.cs
- src/Radical.Windows/Regions/RegionHeaderedElement.cs
- src/Radical.Windows/Regions/TabControlRegion.cs
> Preserve View DataContext on TabItem headers

- src/Radical.Windows.Tests/API/APIApprovals.Approve_API.approved.txt
- src/Radical.Windows/ComponentModel/Regions/ISwitchingElementsRegion.cs
> Add support for "add and activate" on switching elements regions
